version: "2.1"
services:
    localstack:
        image: localstack/localstack
        ports:
          #dynamodb port.
          - "4566:4566"
          #dynamodb shell.
          - "4563:4563"
          - "8080:8080"
        environment: 
          - SERVICES=dynamodb
          - LAMBDA_EXECUTOR=local
          - LAMBDA_REMOTE_DOCKER=false
          - DOCKER_HOST=unix:///var/run/docker.sock
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock